#! /bin/sh

#######################################
### teal's bspwm configuration file ###
###     a tiling window manager     ###
#######################################

###############################
# daemonize startup processes #
###############################

killall -q dunst sxhkd lemonbar polybar redshift lxpolkit
dunst &
sxhkd &
polybar pathfinder &
redshift &
lxpolkit &
xbacklight -set 50
xwallpaper --zoom ~/Pictures/backgrounds/trees.jpg
# $XDG_CONFIG_HOME/bar/barrc | lemonbar -bp -g 1889x25+16+16 -f "NotoSansMono:size=10" -f "Symbola:size=10" &

############################################
# configure window manager characteristics #
############################################

# create ten workspaces
bspc monitor -d I II III IV V VI VII IIX IX X

# configure gaps characteristics
bspc config border_width			8
bspc config window_gap				16
bspc config focused_border_color	"#3C494E"
bspc config normal_border_color		"#29353B"
bspc config active_border_color		"#29353B"
bspc config presel_feedback_color	"#16A085"

# window splitting settings
bspc config split_ratio				0.50
bspc config automatic_scheme		alternate
bspc config center_pseudo_tiled		true

# window focus settings
bspc config click_to_focus			true
bspc config focus_follows_pointer	true
bspc config pointer_follows_monitor	true

# monitor settings
bspc config remove_disabled_monitors	true
bspc config remove_unplugged_monitors	true

##############################################
# open applications with specific conditions #
##############################################

# find application identifier by rofi -i -show window
bspc rule -a Viewnior state=pseudo_tiled
bspc rule -a Parole state=fullscreen # rectangle=1872x1007+16+16 # rectangle=150x150+1746+8
bspc rule -a Lxappearance state=floating
bspc rule -a Pavucontrol state=floating
