#! /bin/sh

#######################################
### teal's bspwm configuration file ###
###     a tiling window manager     ###
#######################################

# https://github.com/addy-dclxvi/void-bspwm-dotfiles - random colorschemes (!)

###################################
### daemonize startup processes ###
###################################

killall -q sxhkd dunst lemonbar polybar
sxhkd &
dunst &
polybar pathfinder &
# lemonbar -g x25 -b -f
feh --bg-scale --no-fehbg ~/Pictures/backgrounds/trees.jpg &
xbacklight -set 50
lxpolkit &

################################################
### configure window manager characteristics ###
################################################

# create ten workspaces
bspc monitor -d I II III IV V VI VII IIX IX X

# configure gaps characteristics
bspc config border_width        8
bspc config window_gap          16
bspc config focused_border_color '#3C494E'
bspc config normal_border_color '#29353B'
bspc config presel_feedback_color '#16A085'

# window split ratio
bspc config split_ratio         0.50

# window focus settings
bspc config click_to_focus          true
bspc config focus_follows_pointer   true
bspc config pointer_follows_monitor true

##################################################
### open applications with specific conditions ###
##################################################

bspc rule -a Org.gnome.Characters state=floating
bspc rule -a mpv state=floating rectangle=150x150+1746+8
# bspc rule -a URxvt state=floating
# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Firefox desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
