#! /bin/bash

########################################################
###        teal's custom lemonbar scripts file       ###
### a featherweight, lemon-scented, bar based on xkb ###
########################################################

################
# dependencies #
################

# checkupdates
# df
# top
# acpi
# nmcli
# xbacklight
# pulsemixer
# date

##############
# workspaces #
##############

# for length of workspaces get them all
# list workspaces as roman numberals
# if statements and then a for loop (for > 10)

# bspwm

# berrywm

# wm toggle script

# current focus

###############
# system tray #
###############

# depends on another application?
# ^ possibly in the center, another option is the current focused window

###########
# updates #
###########

# grinds lemonbar to a fucking halt
_updates() {
	UPDATES=$(checkupdates 2>/dev/null | wc -l)
	test "$UPDATES"-eq 0 || echo "updates: $UPDATES available packages"
}

############
# hardware #
############

_wifi() { # on click: launch a small nmtui?
	echo -n "wifi: "
	nmcli --mode multiline c s --active | grep "NAME" | sed "s/.*  //"
}

# issue: above might not work for >1 networks
# eth

# good speed test: mute and unmute
_audio () { # on click: pactl set-sink-mute 0 toggle
	echo -n "audio: "
	if [ $(pulsemixer --get-mute) -eq 0 ]
	then
		echo "$(pulsemixer --get-volume | sed 's/ .*//')%"
	else
		echo "muted"
	fi
}

_blight() { # on click: xbacklight -set 50
	echo -n "bright: "
	xbacklight -get | sed "s/\..*//"
}

#############
# internals #
#############

# issue: this doesn't give the same results as polybar
# issue: SLOWS DOWN lemonbar i need async
_cpu () {
	echo -n "cpu: "
	echo "$(top -bn 1 | grep 'Cpu' | grep -Eo '([0-9]+\.[0-9] us)' | sed 's/\..*//')%"
}

# ram

_temp() { # internal temperature, in degrees fahrenheit
	echo -n "temp: "
	acpi -tf | grep -Eo "([0-9]*\.[0-9])"
}

_space() { # occupied disk space
	echo -n "$USER: "
	df -k / | grep -Eo "([0-9]+%)"
}

###########
# battery #
###########

_pwr() {
	echo -n "pwr: "
	test "$(acpi | grep 'Discharging')" || printf "⚡"
	acpi | grep -Eo "([0-9]+%)"
}

_until() {
	echo -n "remaining: "
	acpi -b | grep -Eo "([0-9][0-9]:[0-9][0-9])"
}

# interesting stuff:
# acpi -i # degradation

###############
# date / time #
###############

_date() {
	echo -n "date: "
	date "+%a, %b %d"
}

_clock() {
	echo -n "time: "
	date "+%I:%M %P"
}

_pubip () {
	dig +short myip.opendns.com @resolver1.opendns.com
}

_privip() {
	ip addr show | rg wl | awk '/inet/ {print $2}'
}

# datetime toggle script

#########
# power #
#########

# options:
# reboot: reboot
# poweroff: poweroff

#################
# lemonbar loop #
#################

# THIS DESPERATELY NEEDS ASYNC
# IN ANY FORM
{
while :
do
	left="I II III IV V VI VII IIX IX X"
	center="super + / for commands"
	right="$(_wifi) | $(_temp) | $(_space) | $(_pwr) | $(_clock)"
	echo "%{l} $left %{c} $center %{r} $right "
	sleep 1
done
} | lemonbar -pb -g 1889x25+16+16 -f "NotoSansMono:size=11" -f "NotoSansSymbols2-Regular:size=11"

#while true
#do
#    BAR_INPUT="%{l} $(cur) $(tot)%{c}%{r}$(pubip) $(privip) $(drive) $(mem) $(cpu) $(vol) $(pdate)"
#	echo $BAR_INPUT
#	sleep 1
#done
