#!/bin/sh

#########################
### river keybindings ###
#########################

# Use the "logo" key as the primary modifier (Mod4)
mod="Alt"

##########
# basics #
##########

# Launch a terminal
riverctl map normal $mod Return \
    spawn 'kitty'

# Spawn application launcher
riverctl map normal $mod Space \
    spawn 'rofi -i -show drun'

# Spawn window switcher
riverctl map normal $mod+Shift Space \
    spawn 'rofi -i -show window'

# Map swaylock to Mod+BackSpace
riverctl map normal $mod BackSpace spawn "swaylock -i $lockscreen"

# Log out of river
riverctl map normal $mod+Shift BackSpace exit

# Dismiss notification
riverctl map normal $mod Grave \
    spawn 'dunstctl close'

# Show previous notification
riverctl map normal $mod+Shift Grave \
    spawn 'dunstctl history-pop'

# TODO: kill application
# riverctl map normal $mod Q close

# Close the focused view
riverctl map normal $mod W close

# Reload river hotkeys
# riverctl map normal $mod R reload

###################
# layout commands #
###################

# Toggle all currently tagged windows to be floating / tiling
# riverctl map normal $mod T toggle-all-float

# Toggle stacking ("floating")
riverctl map normal $mod S toggle-float

# Toggle fullscreen
riverctl map normal $mod F toggle-fullscreen

# Toggle pseudo-tiling
# riverctl map normal $mod G toggle-pseudo-tiling

# Hide ("minimize") a window (resize to be very small?)
# riverctl map normal $mod N minimize

# Mod+{Up,Right,Down,Left} to change layout orientation
# riverctl map normal $mod Up    send-layout-cmd rivertile "main-location top"
# riverctl map normal $mod Right send-layout-cmd rivertile "main-location right"
# riverctl map normal $mod Down  send-layout-cmd rivertile "main-location bottom"
# riverctl map normal $mod Left  send-layout-cmd rivertile "main-location left"

#################
# moving around #
#################

# Mod+J and Mod+K to focus the next/previous view in the layout stack
riverctl map normal $mod Down focus-view next
riverctl map normal $mod Up focus-view previous

# Mod+Shift+J and Mod+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal $mod+Shift Down swap next
riverctl map normal $mod+Shift Up swap previous

# TODO: what do these do?
# Mod+Period and Mod+Comma to focus the next/previous output
riverctl map normal $mod Period focus-output next
riverctl map normal $mod Comma focus-output previous

# Mod+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal $mod+Shift Period send-to-output next
riverctl map normal $mod+Shift Comma send-to-output previous

# Mod+Return to bump the focused view to the top of the layout stack
# riverctl map normal $mod Return zoom

# Mod+H and Mod+L to decrease/increase the main ratio of rivertile(1)
riverctl map normal $mod Left send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal $mod Right send-layout-cmd rivertile "main-ratio +0.05"

# Mod+Shift+H and Mod+Shift+L to increment/decrement the main count of rivertile(1)
riverctl map normal $mod A send-layout-cmd rivertile "main-count +1"
riverctl map normal $mod D send-layout-cmd rivertile "main-count -1"

# Mod+Alt+{H,J,K,L} to move views
riverctl map normal $mod+Alt Left move left 50
riverctl map normal $mod+Alt Down move down 50
riverctl map normal $mod+Alt Up move up 50
riverctl map normal $mod+Alt Right move right 50

# Mod+Alt+Control+{H,J,K,L} to snap views to screen edges
riverctl map normal $mod+Alt+Control Left snap left
riverctl map normal $mod+Alt+Control Down snap down
riverctl map normal $mod+Alt+Control Up snap up
riverctl map normal $mod+Alt+Control Right snap right

# Mod+Alt+Shif+{H,J,K,L} to resize views
# NOTE: only works on floating windows
riverctl map normal $mod+Alt+Shift Left resize horizontal -50
riverctl map normal $mod+Alt+Shift Down resize vertical 50
riverctl map normal $mod+Alt+Shift Up resize vertical -50
riverctl map normal $mod+Alt+Shift Right resize horizontal 50

##############################
# mouse and gesture controls #
##############################

# move views
riverctl map-pointer normal $mod BTN_LEFT move-view

# resize views
riverctl map-pointer normal $mod BTN_RIGHT resize-view

# switch tags
# riverctl map-pointer normal None SwipeLeft prev-tag
# riverctl map-pointer normal None SwipeRight next-tag

############
# desktops #
############

for i in $(seq 0 9)
do
    tags=$((1 << $i))

    # Mod+[1-9] to focus tag [0-8]
    riverctl map normal $mod $i set-focused-tags $tags

    # Mod+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal $mod+Shift $i set-view-tags $tags

    # Mod+Ctrl+[1-9] to toggle focus of tag [0-8]
    riverctl map normal $mod+Control $i toggle-focused-tags $tags

    # Mod+Shift+Ctrl+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal $mod+Shift+Control $i toggle-view-tags $tags
done

# Mod+Minus to focus all tags
# Mod+Equal to tag focused view with all tags
all_tags=$(((1 << 10) - 1))
riverctl map normal $mod Minus set-focused-tags $all_tags
riverctl map normal $mod Plus set-view-tags $all_tags

##############
# media keys #
##############

# Various media key mapping examples for both normal and locked mode
for mode in normal locked
do
    #################
    # audio / video #
    #################

    riverctl map $mode None XF86AudioMute spawn "pactl set-sink-mute 0 toggle && \
        notify-send -a pactl -u low -r 865863 -i audio-volume-high \
        \"Volume: \$(pulsemixer --get-volume | sed 's/ .*//')%\" \
        \"\$(test \$(pulsemixer --get-mute) -ne 1 || echo 'mute')\""

    riverctl map $mode None XF86AudioLowerVolume spawn "pactl set-sink-volume 0 -5% && \
        notify-send -a pactl -u low -r 865863 -i audio-volume-high \
        \"Volume: \$(pulsemixer --get-volume | sed 's/ .*//')%\" \
        \"\$(test \$(pulsemixer --get-mute) -ne 1 || echo 'mute')\""

    riverctl map $mode None XF86AudioRaiseVolume spawn "pactl set-sink-volume 0 +5% && \
        notify-send -a pactl -u low -r 865863 -i audio-volume-high \
        \"Volume: \$(pulsemixer --get-volume | sed 's/ .*//')%\" \
        \"\$(test \$(pulsemixer --get-mute) -ne 1 || echo 'mute')\""

    #############
    # backlight #
    #############

    riverctl map $mode None XF86MonBrightnessDown spawn "light -U 5 && \
        notify-send -a light -u normal -r 21311 -i xfpm-brightness-lcd \
        \"Backlight: \$(light -G | sed 's/\..*//')%\""

    riverctl map $mode None XF86MonBrightnessUp spawn "light -A 5 && \
        notify-send -a light -u normal -r 21311 -i xfpm-brightness-lcd \
        \"Backlight: \$(light -G | sed 's/\..*//')%\""

    # TODO: XF86Display

    ##############
    # media keys #
    ##############

    riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
    riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioNext  spawn 'playerctl next'

    # NOTE: these fucked up bindings are the result of a ThinkPad keyboard
    # in the future, i may get rid of them if i remap my keyboard on a lower level
    riverctl map $mode None Home   spawn 'playerctl previous'
    riverctl map $mode None End    spawn 'playerctl play-pause'
    riverctl map $mode None Insert spawn 'playerctl next'

    ##################
    # screenshooting #
    ##################

    riverctl map normal None XF86Favorites spawn \
        "grim ~/Pictures/screenshots/\$(date +%Y)/\$(date +%Y-%m-%d-%H%M%S.png) && \
        notify-send -a grim -u low -r 131913 \"Screenshot captured\" \
        \"screen saved to ~/Pictures/screenshots/\$(date +%Y)\""

    # riverctl map normal $mod XF86Favorites spawn \
    #     "notify-send -a grim -u low -r 131913 \"Select an area\" && \
    #     grim ~/Pictures/screenshots/\$(date +%Y)/\$(date +%Y-%m-%d-%H%M%S.png) -g \$(slurp) && \
    #     notify-send -a grim -u low -r 131913 \"Screenshot captured\" \
    #     \"screen saved to ~/Pictures/screenshots/\$(date +%Y)\""
done

####################
# passthrough mode #
####################

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested Wayland compositor
riverctl declare-mode passthrough

# Mod+F11 to enter passthrough mode
riverctl map normal $mod+Shift F11 enter-mode passthrough

# Mod+F11 to return to normal mode
riverctl map passthrough $mod+Shift F11 enter-mode normal

#   `   1   2   3   4   5   6   7   8   9   0   -   =   backspace
#                                               -   =
#   q   w   e   r   t   y   u   i   o   p   [   ]   \
#   q       e   r   t   y   u   i   o   p   [   ]   \
#   tab a   s   d   f   g   h   j   k   l   ;   '   enter
#   tab                 g        hjkl       ;   '
#           z   x   c   v   b   n   m   ,   .   /
#           z   x   c   v   b   n   m   ,   .   /
# grave: notifications numbers: workspaces backspace: lock screen enter: terminal
# w: close
# a and d: "main count" (layout) of rivertile
# s: toggle-floating f: toggle-fullscreen

# future:
# -/+: always on top / always visible
# q: kill program e: ??? r: reload-river t: tile everything []: move to next tag
# g: resize or enter gaps mode hjkl: arrows

# GNOME (for reference)
#   `   1   2   3   4   5   6   7   8   9   0   -   =   backspace
#       1   2   3   4   5   6   7   8   9   0   -   =   lock
#   q   w   e   r   t   y   u   i   o   p   [   ]   \
#   q       e   r   t   y   u   i   o   p   [   ]   \
#   tab a   s   d   f   g   h   j   k   l   ;   '   enter
#                       g        hjkl       ;   '
#           z   x   c   v   b   n   m   ,   .   /
#           z   x   c   v   b           ,   .   /
# grave and tab: switch windows enter: terminal
# w: close f: fullscreen
# a and s and d: media control
# n: notification centre m: hide
