#
# ~/.bashrc
#

##########
# header #
##########

# PS1='\[\033[01;31m\][\h\[\033[01;36m\] \W\[\033[01;31m\]]\$\[\033[00m\] '
# PS1='\[\033[01;32m\][\u@\h\[\033[01;37m\] \W\[\033[01;32m\]]\$\[\033[00m\] '
# PS1='\[\033[01;32m\][🜎 \W\[\033[01;32m\]]\$\[\033[00m\] '
# PS1='\[\033[01;32m\][🜁 \W\[\033[01;32m\]]\$\[\033[00m\] '
PS1='\[\033[01;32m\][🜃 \W\[\033[01;32m\]]\$\[\033[00m\] '

# symbols
# elemental: 🜁🜃🜂🜄
# weather: ☀☼☁
# phi: Φɸφϕ𝜙

#####################
# set shell options #
#####################

shopt -s checkwinsize
shopt -s expand_aliases
shopt -s autocd
shopt -s histappend

###########
# aliases #
###########

alias android-studio='~/Applications/android-studio/bin/studio.sh'
alias bat='bat --pager="less -FR" --paging never'
alias config='git -C $HOME/.config/'
alias clean='sudo pacman -Rs $(pacman -Qqdt)'
alias cp='cp -i'
alias df='df -h'
alias dril='fortune -o dril'
alias grep='grep --colour=auto'
alias ls='ls --color=auto'
alias map='telnet mapscii.me'
alias more='less'
alias neovim='nvim'
alias nv='nvim'
alias q='exit'
alias starwars='telnet towel.blinkenlights.nl'
alias todo='nvim ~/Documents/todo'
alias update='sudo pacman -Syyu'
alias vim='nvim --noplugin'
alias weather='curl https://wttr.in/~Bainbridge+Island?q0'
alias yt='youtube-dl -o "~/Videos/%(title)s-%(id)s.%(ext)s"'

